import AppContextProvider from "@/app/app-context-provider";
import NavBar from "@/components/layout/nav-bar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <AppContextProvider>
          <NavBar />
          <div className="container mx-auto p-4 mt-16">
            {children}
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
